import datetime
import stat
from pathlib import Path
from string import Template
from urllib.parse import quote

from okfy.archetype import Archetype
from okfy.bundle import RESERVED_DIRS, Bundle

PRECOMMIT = """#!/bin/sh
# okfy pre-commit: write-policy gate (ADR-0007) + Spec §9 conformance.
# Sanctioned mutators (okfy review accept / okfy refine) commit --no-verify.
POLICY_LINES=$(grep -c '^write_policy:' meta/purpose.md 2>/dev/null || echo 0)
if [ "$POLICY_LINES" != "1" ]; then
  echo "meta/purpose.md declares write_policy $POLICY_LINES times — expected 1." >&2
  echo "YAML keeps the last, this hook reads the first: two readers, two" >&2
  echo "answers. Fix the frontmatter." >&2
  exit 1
fi
POLICY=$(sed -n 's/^write_policy:[[:space:]]*//p' meta/purpose.md 2>/dev/null | head -1 | tr -d '\\r"'"'"' ')
# Fail-closed on anything that is not one of the two policies. This used to be a
# bare `= proposals` test with no else-branch, so `proposal`, `PROPOSALS` or a
# missing value left the gate inert while the bundle still read as gated.
case "$POLICY" in
  direct)
    ;;                        # the owner opted into direct edits
  proposals)
    # index/ and protocols/ are bundle.RESERVED_DIRS — generated wholly by
    # `okfy package` (index/<dir>.md shards, protocols/memory.md), never by
    # an owner or agent, so a package-only commit is not a "direct concept
    # edit". A real concept hand-placed there is caught by the separate
    # E_RESERVED_DIR check (validate, and package itself before it writes),
    # not by this gate.
    BLOCKED=$(git diff --cached --name-only --diff-filter=ACMRD -- '*.md' \\
      | grep -vE '^(proposals|drafts|index|protocols)/' \\
      | grep -vE '^(index|log|README|AGENTS|CLAUDE)\\.md$')
    if [ -n "$BLOCKED" ]; then
      echo "write_policy=proposals: direct concept edits are refused:" >&2
      echo "$BLOCKED" >&2
      echo "Agents: okfy propose. Owner: okfy refine / okfy review accept." >&2
      echo "Deliberate bypass: git commit --no-verify" >&2
      exit 1
    fi
    ;;
  *)
    echo "write_policy in meta/purpose.md is '$POLICY', not proposals|direct —" >&2
    echo "refusing the commit rather than guessing which gate you meant." >&2
    echo "Deliberate bypass: git commit --no-verify" >&2
    exit 1
    ;;
esac
if command -v okfy >/dev/null 2>&1; then
  okfy validate . --quiet || { echo "okfy validate failed — fix or --no-verify"; exit 1; }
fi
"""


# OKF v0.2 §8: a root index may declare its version, and nothing else.
INDEX_HEAD = '---\nokf_version: "0.2"\n---\n'


DEMOTED_HEADING = "## Not reached by any recorded eval run"


# v0.24 review fix (findings 12/27/28): index/ and protocols/ are
# bundle.RESERVED_DIRS. Before v0.24 they were ordinary concept directories,
# so a pre-v0.24 bundle can still hold an owner concept there — and
# `okfy package` used to delete/overwrite everything under them on the
# assumption the directory was entirely its own output. This first-line
# marker is the recognisability signal that assumption needed: only a file
# that carries it was written by `okfy package`, so only such a file may be
# deleted or overwritten. Anything else under a RESERVED_DIR makes package()
# refuse (E_RESERVED_DIR) before it writes anything at all.
GENERATED_MARKER = "<!-- okfy:generated — do not edit; rewritten by okfy package -->\n"


def _is_generated_file(path: Path) -> bool:
    """True if `path`'s first line is GENERATED_MARKER — the only fact
    package() trusts to tell its own output apart from a file it did not
    write, under a RESERVED_DIR. Not a frontmatter/type check (validate's
    `_check_reserved_dir_concepts` already does that, for a different
    purpose): package needs to know authorship, not whether a file "looks
    like a concept"."""
    try:
        with path.open("r", encoding="utf-8") as f:
            return f.readline() == GENERATED_MARKER
    except OSError:
        return False


def _check_reserved_dirs_are_ours(bundle: Bundle) -> None:
    """Preflight, run before package() writes anything: refuse if index/ or
    protocols/ holds a file package did not generate. Without this, a
    pre-v0.24 bundle's owner concept at e.g. index/sp500.md or a hand-placed
    protocols/memory.md was deleted or overwritten silently — validate's own
    E_RESERVED_DIR diagnostic exists to catch exactly this, but only fires
    AFTER package already destroyed the file, so its "move it" way out never
    worked. Refusing here, first, makes the way out real."""
    for name in sorted(RESERVED_DIRS):
        d = bundle.root / name
        if not d.is_dir():
            continue
        for p in sorted(d.rglob("*.md")):
            if not _is_generated_file(p):
                rel = p.relative_to(bundle.root)
                raise ValueError(
                    f"E_RESERVED_DIR: {rel} is under {name}/, which `okfy "
                    "package` owns and may delete or overwrite — but this "
                    "file was not generated by okfy package (no generated "
                    "marker), so packaging refuses rather than risk "
                    f"destroying it. Move it to another directory (e.g. "
                    f"{name}-notes/) and re-run `okfy package`.")


def _link_target(id_: str) -> str:
    """Percent-encode each `/`-separated segment of a concept/shard id for
    use inside a markdown link target. A directory name containing a space
    or `)` otherwise breaks every reader that parses these links back out —
    `LINK_RE`/`INDEX_LINE_RE` (`[^)\\s]+`) can't include either character in
    a captured target, and neither can validate's `shard_refs` regex. `/` is
    left alone: it is the path separator, not part of any one segment."""
    return "/".join(quote(part, safe="") for part in id_.split("/"))


def _plan_categories(bundle: Bundle) -> dict[str, str]:
    """`categories` on meta/extraction-plan.md: an OPTIONAL owner-approved
    mapping of top-level concept directory -> one-line category description
    (`/okfy:new`'s Extraction Plan step already calls this "category layout"
    in plugin/commands/new.md; this is its first machine-readable form).

    Read-only, copied verbatim by `render_sharded_index` — never reworded,
    never invented for a directory the plan does not mention."""
    plan = bundle.plan()
    cats = plan.meta.get("categories") if plan else None
    return ({str(k): str(v) for k, v in cats.items()}
            if isinstance(cats, dict) else {})


def render_index(bundle: Bundle, demote=frozenset()) -> str:
    """`demote`: ids listed last, under their own heading — still linked, still
    searched by `okfy query`; only their place in the resident index moves."""
    by_type: dict[str, list] = {}
    demoted = []
    for c in bundle.concepts():
        if c.id.startswith("meta/"):
            continue
        if c.id in demote:
            demoted.append(c)
            continue
        by_type.setdefault(str(c.meta.get("type")), []).append(c)
    purpose = bundle.purpose()
    lines = [f"# {purpose.get('title', 'Knowledge Bundle')}", ""]

    def entries(cs):
        return [f"- [{c.meta.get('title', c.id)}]({c.id}.md) — "
                f"{str(c.meta.get('description', '')).strip()}"
                for c in sorted(cs, key=lambda x: x.id)] + [""]
    for t in sorted(by_type):
        lines += [f"## {t}", ""] + entries(by_type[t])
    if demoted:
        lines += [DEMOTED_HEADING, "",
                  "No recorded eval run retrieved these. They are listed last, "
                  "not removed: `okfy query` searches them as before.", ""]
        lines += entries(demoted)
    return INDEX_HEAD + "\n".join(lines)


def _shard_entries(cs, *, root_relative: bool = False) -> list[str]:
    """Line-for-line the same format `render_index`'s local `entries()`
    closure produces — kept as a free function (not shared with it) so the
    flat renderer above stays untouched, since its bytes are a hard invariant
    without `--shard-index`.

    `root_relative`: `index/<dir>.md` files live one directory below
    index.md, so their concept links need a leading `/` (bundle-root-relative
    — `resolve_link` special-cases it) instead of the plain `{id}.md` that is
    correct when the listing itself sits at the bundle root.

    The link target is percent-encoded (`_link_target`) — a concept whose id
    contains a space or `)` (from a directory name with one) would otherwise
    write a target no reader regex can parse back out."""
    prefix = "/" if root_relative else ""
    return [f"- [{c.meta.get('title', c.id)}]({prefix}{_link_target(c.id)}.md) — "
            f"{str(c.meta.get('description', '')).strip()}"
            for c in sorted(cs, key=lambda x: x.id)] + [""]


def render_sharded_index(bundle: Bundle, demote=frozenset()) -> tuple[str, dict[str, str]]:
    """v0.24 (a), opt-in `okfy package --shard-index`: a two-level resident
    index. `index.md` keeps one line per top-level concept directory (plus any
    concept with no directory, and the demoted section, unchanged from flat);
    full per-directory listings — grouped by type, same lines and order the
    flat index prints for that concept set — move to non-resident
    `index/<dir>.md` files under the RESERVED `index/` directory
    (`bundle.RESERVED_DIRS`).

    Returns (resident_index_text, {relpath: content}) — the caller decides
    where the shard files land and prunes stale ones.
    """
    by_dir: dict[str, list] = {}
    top_level = []
    demoted = []
    for c in bundle.concepts():
        if c.id.startswith("meta/"):
            continue
        if c.id in demote:
            demoted.append(c)
            continue
        parts = c.id.split("/", 1)
        if len(parts) == 1:
            top_level.append(c)
        else:
            by_dir.setdefault(parts[0], []).append(c)

    purpose = bundle.purpose()
    cats = _plan_categories(bundle)
    lines = [f"# {purpose.get('title', 'Knowledge Bundle')}", ""]

    if top_level:
        by_type: dict[str, list] = {}
        for c in top_level:
            by_type.setdefault(str(c.meta.get("type")), []).append(c)
        for t in sorted(by_type):
            lines += [f"## {t}", ""] + _shard_entries(by_type[t])

    lines += ["## Directories", ""]
    shard_files: dict[str, str] = {}
    for d in sorted(by_dir):
        cs = by_dir[d]
        n = len(cs)
        desc = cats.get(d)  # verbatim from the plan, or nothing invented
        tail = f" — {desc}" if desc else ""
        lines.append(f"- [{d}/](index/{_link_target(d)}.md) — "
                    f"{n} concept{'s' if n != 1 else ''}{tail}")
        by_type = {}
        for c in cs:
            by_type.setdefault(str(c.meta.get("type")), []).append(c)
        shard_lines = [f"# {d}/", ""]
        for t in sorted(by_type):
            shard_lines += [f"## {t}", ""] + _shard_entries(by_type[t], root_relative=True)
        # `d` (unencoded) is the real relative FILE path — only the markdown
        # LINK to it (above) needs encoding; the filesystem handles a space
        # or `)` in a name fine. GENERATED_MARKER is the recognisability
        # signal _write_shard_files/_clear_shard_dir require before deleting
        # or overwriting a file here (findings 12/27/28).
        shard_files[f"index/{d}.md"] = GENERATED_MARKER + INDEX_HEAD + "\n".join(shard_lines)
    lines.append("")

    if demoted:
        lines += [DEMOTED_HEADING, "",
                  "No recorded eval run retrieved these. They are listed last, "
                  "not removed: `okfy query` searches them as before.", ""]
        lines += _shard_entries(demoted)
    return INDEX_HEAD + "\n".join(lines), shard_files


def render_readme(bundle: Bundle, archetype: Archetype) -> str:
    p = bundle.purpose()
    corpus = bundle.get("meta/corpus")
    counts: dict[str, int] = {}
    for c in bundle.concepts():
        if not c.id.startswith("meta/"):
            t = str(c.meta.get("type"))
            counts[t] = counts.get(t, 0) + 1
    rows = "\n".join(f"| {t} | {n} |" for t, n in sorted(counts.items()))
    return f"""# {p.get('title', 'Knowledge Bundle')}

An [OKF](https://github.com/GoogleCloudPlatform/knowledge-catalog) knowledge bundle,
built with OKFy. Archetype: {archetype.name} v{archetype.version}.

**Purpose:** {p.get('title', '')} — see [meta/purpose.md](meta/purpose.md).
**Corpus:** `{corpus.meta.get('corpus') if corpus else 'unknown'}`
(snapshot {corpus.meta.get('extracted_at') if corpus else '?'}).
**Language:** {p.get('language', 'en')}.

| Type | Concepts |
|---|---|
{rows}

Humans: start at [index.md](index.md). Agents: read [AGENTS.md](AGENTS.md).
"""


# v0.24 (b): the memory block shrank from ~216 tokens of discipline text to a
# pointer, because AGENTS.md is resident context billed on every turn and the
# old block measured 21.7-41% of the resident core on the smallest real
# bundles.
# A test asserts this is <= 60 tokens by okfy's own counter.
MEMORY_BLOCK = """
<!-- okfy:memory -->
Memory is filed as proposals, never written to concepts directly. Before
writing, read `protocols/memory.md` for the full discipline (search first,
gap/flag/supersede, evidence kinds, `okfy fresh`).
<!-- /okfy:memory -->
"""

# The full discipline the pointer above sends an agent to — packaged to the
# NON-resident `protocols/memory.md` (bundle.RESERVED_DIRS), read on demand
# instead of billed every turn. Today's former MEMORY_BLOCK text, plus the
# v0.24 additions the old block predates: gap/flag/supersede actions,
# search-the-user's-wording-first (lexicon notes are phrase-keyed), and
# `okfy fresh` instead of a blind re-read.
MEMORY_PROTOCOL = """# Memory: before and after a task

- **Before:** `okfy query` the task's own terms. For each hit you rely on, check
  `stale` (owner: do not trust as current) and `review_due` (a passed reminder:
  verify before relying — not the same as stale).
- **After:** propose only what an agent with a blank context would need — a
  confirmed root cause, a decision with its reasons, a constraint, a
  reproducible workaround. Never conversation, scratch work or guesses.
- Search first; add to an existing concept with `--extends <id>`.
- `okfy propose <bundle> --as <actor> --evidence <kind>=<ref> …` — kinds:
  test-run, owner-decision, external-source, agent-inference.
- Something is remembered only when propose returned a proposal id; it is
  accepted only after `okfy review accept`. Refusal codes name their way out.

## v0.24 additions

- **Search the user's own wording first**, before rewriting into canonical
  terms — lexicon coverage notes (`not-covered`, `ambiguous`) are phrase-keyed
  and can miss a rewritten query that would have fired on the original words.
- **A gap, a flag, or a supersede is also memory.** Could not answer at all:
  `--action gap --query "<the user's wording>"`. Something is wrong but not
  yours to fix: `--action flag --type <kind> --target <id>`. New evidence
  replaces a conclusion rather than adding to it: `--action supersede
  --target <old-id> --new-id <new-id>` — the old concept stays, marked stale.
- **Check freshness, don't re-read.** Before relying on a concept read earlier
  in a long session, `okfy fresh` (MCP: `okfy_fresh`) against its earlier
  `sha256` instead of re-fetching it.
"""

# v0.24 (a), rendered only when the bundle is packaged `--shard-index`: the
# one sentence telling an agent the index is two-level. Kept under 30 tokens
# (a test asserts it), and substituted as `$index_note` at the END of an
# existing line — no leading/trailing newline of its own, so the flat-mode
# empty-string substitution reproduces today's line byte-for-byte and the
# sharded sentence reads as one continued sentence rather than a new
# paragraph (which would have shifted blank-line spacing either way).
INDEX_SHARD_NOTE = (
    " The index is two-level: open `index/<dir>.md` for a directory's full "
    "listing, or use `okfy query`.")


def render_agents_md(bundle: Bundle, archetype: Archetype, shard: bool = False) -> str:
    """The consumption protocol an agent reads instead of the CLI.

    Types and layout come from the PLAN when it declares them, because the plan
    is what the bundle was actually built to. Rendering the archetype's canonical
    list meant an adapted bundle shipped an AGENTS.md that omitted its own custom
    types and advertised archetype types it does not contain — a consumption
    contract describing a different bundle.

    `shard`: whether this bundle is being packaged with `--shard-index` —
    substitutes the one-sentence `$index_note` a template may carry.

    Strict `substitute`, not `safe_substitute`: a template placeholder this
    function does not know to fill (a typo, or a new `$foo` a template author
    added without updating this call) must raise, not ship a literal `$foo`
    into every bundle's AGENTS.md. Every caller — every archetype's
    `agents.tmpl` and every test that renders one directly — supplies exactly
    the five names below."""
    p = bundle.purpose()
    tmpl = Template((archetype.root / archetype.consumption_protocol).read_text(encoding="utf-8"))
    plan = bundle.plan()
    declared = (plan.meta.get("types") if plan else None)
    types = ([str(t) for t in declared] if isinstance(declared, (dict, list))
             else list(archetype.canonical_types))
    layout = dict(archetype.layout)
    plan_layout = (plan.meta.get("layout") if plan else None)
    if isinstance(plan_layout, dict):
        layout.update({str(k): str(v) for k, v in plan_layout.items()})
    types_rows = "\n".join(f"- **{t}** — files under `{layout.get(t, './')}`"
                           for t in types)
    text = tmpl.substitute(
        purpose_title=p.get("title", ""), language=p.get("language", "en"),
        write_policy=p.get("write_policy", "proposals"),
        types_table=types_rows,
        index_note=(INDEX_SHARD_NOTE if shard else "")).rstrip("\n") + "\n"
    # v0.24 (b): a memory block only where write_policy actually allows
    # proposals — `direct` (and any other/absent policy) has no propose flow
    # for the block to point at, so rendering it there described a door that
    # is not open. See the "Capability-gated surface" design note.
    if str(p.get("write_policy", "")) == "proposals":
        text += MEMORY_BLOCK
    return text


def append_log(bundle: Bundle, message: str) -> None:
    log = bundle.root / "log.md"
    today = datetime.date.today().isoformat()
    text = log.read_text(encoding="utf-8") if log.is_file() else "# Log\n"
    marker = f"## {today}"
    if marker in text:
        text = text.replace(marker, f"{marker}\n\n- {message}", 1)
    else:
        text = text.rstrip("\n") + f"\n\n{marker}\n\n- {message}\n"
    log.write_text(text, encoding="utf-8")


def install_precommit(bundle: Bundle) -> None:
    hooks = bundle.root / ".git" / "hooks"
    if not hooks.parent.is_dir():
        return  # not a git repo (tests, exotic setups) — silently skip
    hooks.mkdir(exist_ok=True)
    hook = hooks / "pre-commit"
    hook.write_text(PRECOMMIT, encoding="utf-8")
    hook.chmod(hook.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write_shard_files(bundle: Bundle, shard_files: dict[str, str]) -> None:
    """Write `index/<dir>.md` and remove any leftover shard file this run did
    not regenerate — the shard set is fully generated, never hand-authored,
    so a stale one is deleted rather than left to drift (same reasoning as
    `_clear_shard_dir` below when sharding is turned off).

    Only a leftover that carries GENERATED_MARKER is ever unlinked (findings
    12/27/28) — `package()` already refuses via
    `_check_reserved_dirs_are_ours` before reaching here if anything else is
    present, but the check is repeated so this function stays safe to call
    on its own."""
    shard_dir = bundle.root / "index"
    shard_dir.mkdir(exist_ok=True)
    keep = set()
    for rel, text in shard_files.items():
        p = bundle.root / rel
        p.write_text(text, encoding="utf-8")
        keep.add(p)
    for existing in shard_dir.glob("*.md"):
        if existing not in keep and _is_generated_file(existing):
            existing.unlink()


def _clear_shard_dir(bundle: Bundle) -> None:
    """Repackaging WITHOUT `--shard-index` returns a previously-sharded
    bundle to flat: `index/` is entirely generated output, so it is removed
    rather than left behind to describe a shape the resident index no longer
    has.

    Only files carrying GENERATED_MARKER are unlinked (findings 12/27/28);
    anything else already made `package()` refuse before this ran."""
    shard_dir = bundle.root / "index"
    if not shard_dir.is_dir():
        return
    for p in shard_dir.glob("*.md"):
        if _is_generated_file(p):
            p.unlink()
    try:
        shard_dir.rmdir()
    except OSError:
        pass  # something else is in there — not ours to remove


def _write_memory_protocol(bundle: Bundle, write_policy: str) -> None:
    """`protocols/memory.md` (v0.24 (b)) exists exactly when the pointer in
    AGENTS.md points at something — i.e. only under write_policy=proposals.
    Otherwise any stale copy from an earlier policy is removed, the same
    generated-output discipline as the index shards above.

    The file opens with GENERATED_MARKER, and is only unlinked when it
    carries that marker (findings 12/27/28) — `package()` refuses earlier
    via `_check_reserved_dirs_are_ours` if a hand-authored
    protocols/memory.md is present, but this function stays safe standalone."""
    p = bundle.root / "protocols" / "memory.md"
    if write_policy == "proposals":
        p.parent.mkdir(exist_ok=True)
        p.write_text(GENERATED_MARKER + MEMORY_PROTOCOL, encoding="utf-8")
    elif p.is_file() and _is_generated_file(p):
        p.unlink()
        try:
            p.parent.rmdir()
        except OSError:
            pass  # not empty — something else lives under protocols/


def package(bundle: Bundle, archetype: Archetype, demote_unretrieved: bool = False,
           shard_index: bool = False) -> None:
    import json

    from okfy.validate import package_fingerprint
    # Findings 12/27/28: refuse before any write if index/ or protocols/
    # holds a file package did not generate — a pre-v0.24 bundle can still
    # have an owner concept there, and deleting/overwriting it first made
    # E_RESERVED_DIR's "move it" way out a no-op.
    _check_reserved_dirs_are_ours(bundle)
    demote = frozenset()
    if demote_unretrieved:   # opt-in: the signal is bounded by the query set
        from okfy.budget import usage_report
        demote = frozenset(usage_report(bundle)["zero_hit_ids"])
    if shard_index:
        resident_index, shard_files = render_sharded_index(bundle, demote)
        _write_shard_files(bundle, shard_files)
    else:
        resident_index = render_index(bundle, demote)
        _clear_shard_dir(bundle)
    (bundle.root / "index.md").write_text(resident_index, encoding="utf-8")
    (bundle.root / "README.md").write_text(render_readme(bundle, archetype), encoding="utf-8")
    (bundle.root / "AGENTS.md").write_text(
        render_agents_md(bundle, archetype, shard=shard_index), encoding="utf-8")
    (bundle.root / "CLAUDE.md").write_text("@AGENTS.md\n", encoding="utf-8")
    _write_memory_protocol(bundle, str(bundle.purpose().get("write_policy", "")))
    # fingerprint of the concept set the generated docs describe — any later
    # mutation makes the package provably stale (validate --strict-package)
    # Refresh the retrieval cache here too. Packaging is the point at which the
    # bundle's contents are declared final, and leaving the cache behind meant
    # `refine → package → eval run → accept` recorded evidence gathered from a
    # pre-edit index. `okfy index` and this are the only writers.
    from okfy.index import build_index, retrieval_digest, save_index
    from okfy.memory import accepted_since
    idx = build_index(bundle)
    # The manifest is tracked, so the digests it records are the reviewable claim
    # about what build_index produces — which is what makes the gitignored cache
    # trustable at all. Written before save_index so the cache lands against a
    # manifest that already describes it.
    manifest = {"schema": "okfy-package@1",
               "fingerprint": package_fingerprint(bundle),
               "index_content_fingerprint": idx["content_fingerprint"],
               "retrieval_digest": retrieval_digest(idx),
               "memory_accepted": accepted_since(bundle, None)}
    if shard_index:   # absent (not "flat") when not sharded — see validate._index_mode
        manifest["index"] = "sharded"
    (bundle.root / "meta" / "package.json").write_text(
        json.dumps(manifest) + "\n", encoding="utf-8")
    save_index(bundle, idx)
    install_precommit(bundle)
    append_log(bundle, "package: regenerated index.md, README.md, AGENTS.md, "
                       "retrieval index")


def package_workspace(ws) -> None:
    """README + AGENTS.md + CLAUDE.md for a Workspace (self-teaching, ADR-0009)."""
    from importlib import resources
    from string import Template
    tmpl_path = Path(str(resources.files("okfy"))) / "templates" / "workspace-agents.tmpl"
    rows = "\n".join(
        f"- **{m.name}** (role: {m.role}) — `{m.path}`" for m in ws.members)
    queries = ws.meta.get("test_queries") or []
    qnote = ("\n## Acceptance queries\n\n" +
             "\n".join(f"- {q}" for q in queries) + "\n") if queries else ""
    agents = Template(tmpl_path.read_text(encoding="utf-8")).substitute(
        title=ws.meta.get("title", "Workspace"), members_table=rows,
        queries_note=qnote)
    (ws.root / "AGENTS.md").write_text(agents, encoding="utf-8")
    (ws.root / "CLAUDE.md").write_text("@AGENTS.md\n", encoding="utf-8")
    (ws.root / "README.md").write_text(
        f"# {ws.meta.get('title', 'Workspace')}\n\n"
        f"An OKFy federation workspace: no knowledge of its own, only the\n"
        f"manifest, roles, and reviewed crosswalks over these member bundles:\n\n"
        f"{rows}\n\nAgents: read [AGENTS.md](AGENTS.md). "
        f"Humans: `okfy query {ws.root} \"...\"`.\n", encoding="utf-8")
    append_log_ws = ws.root / "log.md"
    if append_log_ws.is_file():
        b = Bundle.__new__(Bundle)          # append_log needs only .root
        b.root = ws.root
        append_log(b, "package: regenerated README.md, AGENTS.md")
